import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Layout from "@/components/layout";
import clsx from "clsx";

import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MetastudioApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" >
      <body
        className={clsx(
          "h-screen antialiased  ",
          inter.className
        )}
      >
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
